[package]
name = "anvm-launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anvm-ast = { path = "../ast" }
anvm-binary-parser = { path = "../binary-parser" }
anvm-disassembly = { path = "../disassembly" }

[dev-dependencies]
pretty_assertions = "1.2.1"
