[package]
name = "anvm-binary-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anvm-ast = {path="../ast"}

[dev-dependencies]
pretty_assertions = "1.2.1"
