[workspace]
members = [
    "crates/ast",
    "crates/disassembly",
    "crates/binary-parser",
    "crates/engine",
    "crates/native-wasi",
    "crates/native-alloc",
    "crates/launcher",
    "crates/debugger",
]
