[package]
name = "anvm-tools"
version = "0.1.0"
edition = "2021"

# [[bin]]
# name = "anvm-asm"
# path = "bin/anvm-asm.rs"

[dependencies]
anvm-ast = { path = "../ast" }
anvm-binary-parser = { path = "../binary-parser" }
anvm-disassembly = { path = "../disassembly" }
