[package]
name = "anvm-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anvm-ast = { path = "../ast" }

[dev-dependencies]
anvm-binary-parser = { path = "../binary-parser" }
pretty_assertions = "1.2.1"
